In [1]:
from utils import pr , measure_time
import numpy as np

In [2]:
x = np.array(
    [
        [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
        [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]
    ]
)
pr(x.shape , 'x.shape')

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----



(2, 2, 3)

In [3]:
mask = x > 6
pr(mask , 'mask')
pr(mask.shape , 'mask.shape')

+++++++++++++++++ mask ++++++++++++++++++
<class 'numpy.ndarray'>
[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]]
-----

+++++++++++++++++ mask.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----



(2, 2, 3)

In [4]:
x[mask]

array([ 7.,  8.,  9., 10., 11., 12.])

In [5]:
y = np.where(x> 6 , x , 0)
pr(y,'y')
pr(y.shape,'y.shape')

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ y.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----



(2, 2, 3)

In [6]:
y = np.maximum(5,x)
pr(y, 'y')
pr(y.shape, 'y.shape')

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 5.  5.  5.]
  [ 5.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ y.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----



(2, 2, 3)

In [7]:
y = np.clip(x, 2, 4)
pr(y , 'y')
pr(y.shape , 'y.shape')

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[[[2. 2. 3.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]]]
-----

+++++++++++++++++ y.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----



(2, 2, 3)

In [8]:
pr(x,'x')
pr(x.shape,'x.shape')
thresholds = np.array([5.0 , 8.0 , 11.0])
pr( thresholds,'thresholds' )
pr( thresholds.shape,'thresholds.shape' )
mask = x > thresholds
pr(mask , 'mask')
pr(mask.shape , 'mask.shape')
approved_values = x[mask]
pr(approved_values , 'approved_values')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----

+++++++++++++++++ thresholds ++++++++++++++++++
<class 'numpy.ndarray'>
[ 5.  8. 11.]
-----

+++++++++++++++++ thresholds.shape ++++++++++++++++++
<class 'tuple'>
(3,)
-----

+++++++++++++++++ mask ++++++++++++++++++
<class 'numpy.ndarray'>
[[[False False False]
  [False False False]]

 [[ True False False]
  [ True  True  True]]]
-----

+++++++++++++++++ mask.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----

+++++++++++++++++ approved_values ++++++++++++++++++
<class 'numpy.ndarray'>
[ 7. 10. 11. 12.]
-----



array([ 7., 10., 11., 12.])