In [1]:
import time
import numpy as np
from typing import  TypeVar 
T = TypeVar('T')
def pr(value:T , title:str|None = None)->T:
    if title :
        print(f'+++++++++++++++++ {title} ++++++++++++++++++')
    else :
        print(f'+++++++++++++++++++++++++++++++++++')
        
    print(type(value))
    print(value)
    print('-----')
    print('')
    return value
def measure_time(func):
    def wrapper(*args,  **kwargs):
        start_time = time.time()
        func(*args, **kwargs)
        end_time = time.time()
        pr(f"{end_time - start_time} seconds" , 'Execution time')
    return wrapper


In [2]:
v = np.array([1.0, 2.0, 3.0])
pr(v, 'v')
pr(v.shape , 'v.shape')

+++++++++++++++++ v ++++++++++++++++++
<class 'numpy.ndarray'>
[1. 2. 3.]
-----

+++++++++++++++++ v.shape ++++++++++++++++++
<class 'tuple'>
(3,)
-----



(3,)

In [3]:
pr(v*2 , 'v*2')
pr(v+v , 'v+v')

+++++++++++++++++ v*2 ++++++++++++++++++
<class 'numpy.ndarray'>
[2. 4. 6.]
-----

+++++++++++++++++ v+v ++++++++++++++++++
<class 'numpy.ndarray'>
[2. 4. 6.]
-----



array([2., 4., 6.])