In [1]:
from utils import pr , measure_time
import numpy as np

In [2]:
# create an implicit random number generator.
rng = np.random.default_rng(seed=42)
pr(rng, 'rng')

+++++++++++++++++ rng ++++++++++++++++++
<class 'numpy.random._generator.Generator'>
Generator(PCG64)
-----



Generator(PCG64) at 0x22CD03EECE0

In [3]:
x = np.array([
    [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]
])
noise = rng.normal(loc=0.0 , scale=0.1 , size=x.shape)
pr(x , 'x')
pr(noise , 'noise')
y = x + noise
pr(y , 'y')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ noise ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 0.03047171 -0.10399841  0.07504512]
  [ 0.09405647 -0.19510352 -0.13021795]]

 [[ 0.01278404 -0.03162426 -0.00168012]
  [-0.08530439  0.0879398   0.07777919]]]
-----

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.03047171  1.89600159  3.07504512]
  [ 4.09405647  4.80489648  5.86978205]]

 [[ 7.01278404  7.96837574  8.99831988]
  [ 9.91469561 11.0879398  12.07777919]]]
-----



array([[[ 1.03047171,  1.89600159,  3.07504512],
        [ 4.09405647,  4.80489648,  5.86978205]],

       [[ 7.01278404,  7.96837574,  8.99831988],
        [ 9.91469561, 11.0879398 , 12.07777919]]])

In [4]:
parent_noise = rng.normal(loc=0,scale=0.1,size=(2,2,1))
pr(parent_noise , 'parent_noise')
pr(x , 'x')
pr(x + parent_noise , 'x + parent_noise')

+++++++++++++++++ parent_noise ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 0.00660307]
  [ 0.11272412]]

 [[ 0.04675093]
  [-0.08592925]]]
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x + parent_noise ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.00660307  2.00660307  3.00660307]
  [ 4.11272412  5.11272412  6.11272412]]

 [[ 7.04675093  8.04675093  9.04675093]
  [ 9.91407075 10.91407075 11.91407075]]]
-----



array([[[ 1.00660307,  2.00660307,  3.00660307],
        [ 4.11272412,  5.11272412,  6.11272412]],

       [[ 7.04675093,  8.04675093,  9.04675093],
        [ 9.91407075, 10.91407075, 11.91407075]]])