In [1]:
import time
import numpy as np
from typing import  TypeVar 
T = TypeVar('T')
def pr(value:T , title:str|None = None)->T:
    if title :
        print(f'+++++++++++++++++ {title} ++++++++++++++++++')
    else :
        print(f'+++++++++++++++++++++++++++++++++++')
        
    print(type(value))
    print(value)
    print('-----')
    print('')
    return value
def measure_time(func):
    def wrapper(*args,  **kwargs):
        start_time = time.time()
        func(*args, **kwargs)
        end_time = time.time()
        pr(f"{end_time - start_time} seconds" , 'Execution time')
    return wrapper


In [2]:
x = np.array([1,2,3,4,5])
y = x[1:4]
pr(x , 'x')
pr(y , 'y')
y[0] = 100
pr(x , 'x')
pr(y , 'y')
pr(y.base , 'this prints x array')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[1 2 3 4 5]
-----

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[2 3 4]
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[  1 100   3   4   5]
-----

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[100   3   4]
-----

+++++++++++++++++ this prints x array ++++++++++++++++++
<class 'numpy.ndarray'>
[  1 100   3   4   5]
-----



array([  1, 100,   3,   4,   5])