In [1]:
from utils import pr
from utils import measure_time
import numpy as np

In [5]:
x = np.array(
    [
        [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
        [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]],
        [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
        [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]],
    ]
)
pr(x, "x")
pr(x.shape, "x.shape")

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(4, 2, 3)
-----



(4, 2, 3)

In [6]:
sum = np.sum(x)
pr(sum , 'sum')

+++++++++++++++++ sum ++++++++++++++++++
<class 'numpy.float64'>
156.0
-----



np.float64(156.0)

In [7]:

pr(x , 'x')
pr(x.shape , 'x.shape')
axis_2_sum = np.sum(x , axis=2)
pr(axis_2_sum , 'axis_2_sum')
pr(axis_2_sum.shape , 'axis_2_sum shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(4, 2, 3)
-----

+++++++++++++++++ axis_2_sum ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 6. 15.]
 [24. 33.]
 [ 6. 15.]
 [24. 33.]]
-----

+++++++++++++++++ axis_2_sum shape ++++++++++++++++++
<class 'tuple'>
(4, 2)
-----



(4, 2)

In [8]:
pr(x , 'x')
pr(x.shape , 'x.shape')
axis_1_sum = np.sum(x , axis=1)
pr(axis_1_sum , 'axis_1_sum')
pr(axis_1_sum.shape , 'axis_1_sum shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(4, 2, 3)
-----

+++++++++++++++++ axis_1_sum ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 5.  7.  9.]
 [17. 19. 21.]
 [ 5.  7.  9.]
 [17. 19. 21.]]
-----

+++++++++++++++++ axis_1_sum shape ++++++++++++++++++
<class 'tuple'>
(4, 3)
-----



(4, 3)

In [9]:
pr(x , 'x')
pr(x.shape , 'x.shape')
axis_0_sum = np.sum(x , axis=0)
pr(axis_0_sum , 'axis_0_sum')
pr(axis_0_sum.shape , 'axis_0_sum shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(4, 2, 3)
-----

+++++++++++++++++ axis_0_sum ++++++++++++++++++
<class 'numpy.ndarray'>
[[16. 20. 24.]
 [28. 32. 36.]]
-----

+++++++++++++++++ axis_0_sum shape ++++++++++++++++++
<class 'tuple'>
(2, 3)
-----



(2, 3)

In [7]:
pr(x , 'x')
pr(x.shape , 'x.shape')
axis_2_sum = np.sum(x , axis=2 )
pr(axis_2_sum , 'axis_2_sum')
pr(axis_2_sum.shape , 'axis_2_sum shape')
axis_2_sum_keepdims = np.sum(x , axis=2 , keepdims=True)
pr(axis_2_sum_keepdims , 'axis_2_sum_keepdims')
pr(axis_2_sum_keepdims.shape , 'axis_2_sum_keepdims shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 3)
-----

+++++++++++++++++ axis_2_sum ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 6. 15.]
 [24. 33.]]
-----

+++++++++++++++++ axis_2_sum shape ++++++++++++++++++
<class 'tuple'>
(2, 2)
-----

+++++++++++++++++ axis_2_sum_keepdims ++++++++++++++++++
<class 'numpy.ndarray'>
[[[ 6.]
  [15.]]

 [[24.]
  [33.]]]
-----

+++++++++++++++++ axis_2_sum_keepdims shape ++++++++++++++++++
<class 'tuple'>
(2, 2, 1)
-----



(2, 2, 1)

In [8]:
x = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7 , 8]
    ])
pr(x , 'x')
pr(x.shape , 'x.shape')
sum_axis_1 = np.sum(x , axis=1)
pr(sum_axis_1 , 'sum_axis_1')
pr(sum_axis_1.shape , 'sum_axis_1.shape')
sum_axis_0 = np.sum(x , axis=0)
pr(sum_axis_0 , 'sum_axis_0')
pr(sum_axis_0.shape , 'sum_axis_0.shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(2, 4)
-----

+++++++++++++++++ sum_axis_1 ++++++++++++++++++
<class 'numpy.ndarray'>
[10 26]
-----

+++++++++++++++++ sum_axis_1.shape ++++++++++++++++++
<class 'tuple'>
(2,)
-----

+++++++++++++++++ sum_axis_0 ++++++++++++++++++
<class 'numpy.ndarray'>
[ 6  8 10 12]
-----

+++++++++++++++++ sum_axis_0.shape ++++++++++++++++++
<class 'tuple'>
(4,)
-----



(4,)