In [1]:
import time
import numpy as np
from typing import  TypeVar 
T = TypeVar('T')
def pr(value:T , title:str|None = None)->T:
    if title :
        print(f'+++++++++++++++++ {title} ++++++++++++++++++')
    else :
        print(f'+++++++++++++++++++++++++++++++++++')
        
    print(type(value))
    print(value)
    print('-----')
    print('')
    return value
def measure_time(func):
    def wrapper(*args,  **kwargs):
        start_time = time.time()
        func(*args, **kwargs)
        end_time = time.time()
        pr(f"{end_time - start_time} seconds" , 'Execution time')
    return wrapper


In [2]:
data = [1,2,3,4,5,6]
pr(data , 'data?')
for x in data : 
    pr(x , 'x')

+++++++++++++++++ data? ++++++++++++++++++
<class 'list'>
[1, 2, 3, 4, 5, 6]
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
1
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
2
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
3
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
4
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
5
-----

+++++++++++++++++ x ++++++++++++++++++
<class 'int'>
6
-----



In [3]:
data = ['1', 2 , 3 , 'hello world']
data.append(True)
pr(data , 'lists allow semantic nonsense')

+++++++++++++++++ lists allow semantic nonsense ++++++++++++++++++
<class 'list'>
['1', 2, 3, 'hello world', True]
-----



['1', 2, 3, 'hello world', True]

In [4]:
a = [1,2,3]
b = [4,5,6]
pr(a+b , 'Arithmetic on lists is not math')

+++++++++++++++++ Arithmetic on lists is not math ++++++++++++++++++
<class 'list'>
[1, 2, 3, 4, 5, 6]
-----



[1, 2, 3, 4, 5, 6]

In [5]:
arr = np.array([1,2,3,4,5,6])
pr(arr , 'array')

+++++++++++++++++ array ++++++++++++++++++
<class 'numpy.ndarray'>
[1 2 3 4 5 6]
-----



array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
pr(a+b , 'Now arithmetic becomes math')

+++++++++++++++++ Now arithmetic becomes math ++++++++++++++++++
<class 'numpy.ndarray'>
[5 7 9]
-----



array([5, 7, 9])

In [7]:
@measure_time
def func1():
    total = 0 
    for x in range(10_000_000):
        total += x
    pr(total , 'func1 total')
@measure_time
def func2():
    arr = np.arange(10_000_000)
    total = arr.sum()
    pr(total , 'func2 total')
func1()
func2()

+++++++++++++++++ func1 total ++++++++++++++++++
<class 'int'>
49999995000000
-----

+++++++++++++++++ Execution time ++++++++++++++++++
<class 'str'>
0.6709198951721191 seconds
-----

+++++++++++++++++ func2 total ++++++++++++++++++
<class 'numpy.int64'>
49999995000000
-----

+++++++++++++++++ Execution time ++++++++++++++++++
<class 'str'>
0.027615070343017578 seconds
-----

