In [1]:
import time
import numpy as np
from typing import  TypeVar 
T = TypeVar('T')
def pr(value:T , title:str|None = None)->T:
    if title :
        print(f'+++++++++++++++++ {title} ++++++++++++++++++')
    else :
        print(f'+++++++++++++++++++++++++++++++++++')
        
    print(type(value))
    print(value)
    print('-----')
    print('')
    return value
def measure_time(func):
    def wrapper(*args,  **kwargs):
        start_time = time.time()
        func(*args, **kwargs)
        end_time = time.time()
        pr(f"{end_time - start_time} seconds" , 'Execution time')
    return wrapper


In [2]:
x  = np.array([2,3,5])
y = np.array([2,2,2])
pr(x*y )

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>
[ 4  6 10]
-----



array([ 4,  6, 10])

In [3]:
z = []
for i in range(len(x)) : 
    z.append(x[i]*y[i])
pr(z)

+++++++++++++++++++++++++++++++++++
<class 'list'>
[np.int64(4), np.int64(6), np.int64(10)]
-----



[np.int64(4), np.int64(6), np.int64(10)]

In [4]:
x = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
y = np.array([1,2,3])
pr(x*y)

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>
[[ 1.  4.  9.]
 [ 4. 10. 18.]]
-----



array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])