In [1]:
import time
import numpy as np
from typing import  TypeVar 
T = TypeVar('T')
def pr(value:T , title:str|None = None)->T:
    if title :
        print(f'+++++++++++++++++ {title} ++++++++++++++++++')
    else :
        print(f'+++++++++++++++++++++++++++++++++++')
        
    print(type(value))
    print(value)
    print('-----')
    print('')
    return value
def measure_time(func):
    def wrapper(*args,  **kwargs):
        start_time = time.time()
        func(*args, **kwargs)
        end_time = time.time()
        pr(f"{end_time - start_time} seconds" , 'Execution time')
    return wrapper


In [2]:
x = np.array([
     [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
y = np.array([10.0, 20.0, 30.0])
pr(x , 'x')
pr(x.shape , 'x.shape')
pr(y , 'y')
pr(y.shape , 'y.shape')
pr(x*y , 'x*y')


+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]]
-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>
(2, 3)
-----

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[10. 20. 30.]
-----

+++++++++++++++++ y.shape ++++++++++++++++++
<class 'tuple'>
(3,)
-----

+++++++++++++++++ x*y ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 10.  40.  90.]
 [ 40. 100. 180.]]
-----



array([[ 10.,  40.,  90.],
       [ 40., 100., 180.]])

In [3]:
y_expanded = np.array([[10.0, 20.0, 30.0] , [10.0, 20.0, 30.0],])
pr(x*y_expanded,'x*y_expanded')


+++++++++++++++++ x*y_expanded ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 10.  40.  90.]
 [ 40. 100. 180.]]
-----



array([[ 10.,  40.,  90.],
       [ 40., 100., 180.]])

In [4]:
y = np.array([2])
pr(x , 'x')
pr(y, 'y')
pr(x*y  , 'x*y')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]]
-----

+++++++++++++++++ y ++++++++++++++++++
<class 'numpy.ndarray'>
[2]
-----

+++++++++++++++++ x*y ++++++++++++++++++
<class 'numpy.ndarray'>
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
-----



array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])